### ISSUE TITLE
rng0 config key documented in release but not actually in release

### ISSUE THREAD

**Issue by AaronSeibert** [hashicorp/packer-plugin-proxmox#224]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

There have been a few PRs and documentation updates around adding a Virtio RNG config (rng0). It is listed in the documentation for 1.1.3, however viewing the tagged code for 1.1.3 it is not actually in the plugin and trying to use it with 1.1.3 emits an error:

```
❯ packer validate .
Error: Unsupported block type

  on ubuntu-live-server.pkr.hcl line 24:
  (source code not available)

Blocks of type "rng0" are not expected here.
```

#### Reproduction Steps

Ensure you are running 1.1.3 of the proxmox plugin and try to configure a rng0 device:

```
 rng0 {
    source = "/dev/urandom"
    max_bytes = 1034
  }
```

### Plugin and Packer version

packer version
Packer v1.9.2

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

```
source "proxmox-iso" "ubuntu-live-server" {

  # ISO
  iso_url          = "https://releases.ubuntu.com/releases/${var.ubuntu_version}/ubuntu-${var.ubuntu_version}-live-server-amd64.iso"
  iso_checksum     = "file:https://releases.ubuntu.com/releases/${var.ubuntu_version}/SHA256SUMS"
  iso_storage_pool = "cephfs"

  # Boot Options
  boot_command = [
    "e<down><down><down><end>",
    "<bs><bs><bs><bs>",
    "autoinstall quiet ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/",
    "<f10>"
  ]
  boot_wait        = "5s"
  ssh_wait_timeout = "15m"

  network_adapters {
    bridge   = "vmbr0"
    vlan_tag = "161"
    model    = "virtio"
  }

  rng0 {
    source = "/dev/urandom"
    max_bytes = 1034
  }

  disks {
    type         = "virtio"
    disk_size    = "20G"
    storage_pool = "vm_disks"
    format       = "qcow2"
    cache_mode   = "writeback"
  }

  http_content = {
    "/user-data" = templatefile(
      "${path.root}/templates/subiquity-autoinstall.yml.j2", {
        user_data = indent(4, templatefile(
          "${path.root}/templates/user-data.yml.j2", {}
        ))
      }
    ),
    "/meta-data" = templatefile(
      "${path.root}/templates/meta-data.yml.j2", {}
    )
  }

  node         = "${var.proxmox_build_node}"
  os           = "l26"
  token        = "${var.proxmox_api_key}"
  proxmox_url  = "${var.proxmox_api_url}"
  username     = "${var.proxmox_api_id}"
  ssh_username = "${var.proxmox_ssh_username}"
  unmount_iso  = true

  vm_id                    = 9000
  insecure_skip_tls_verify = true

  # CPU/RAM
  sockets = 1
  cores   = 4
  memory  = 4096

  template_description = "microk8s node image for quick horizontal scaling"
  template_name        = "microk8s-node"

  cloud_init = true
}
```

### Operating system and Environment details

Not sure that it's necessary, but MacOS (Apple Silicon)

### Log Fragments and crash.log files

Again, the rng0 updates aren't in the tagged 1.1.3 code but they are in the current documentation labeled 1.1.3

**Comment by Sad-Soul-Eater** [comment]
Same situation with disks `discard` and `ssd` options

**Comment by mabeett** [comment]
Same problems in Linux amd64.
 I've just tested with packer version `1.9.4`. and plugin  version `v1.1.3` in  `Debian GNU/Linux 12 (bookworm)`.

**Comment by lbajolet-hashicorp** [comment]
Hi,

This was indeed a mistake on our part, the latest version of the plugin (v1.1.5) released yesterday has support for those attributes.

I presume the error happened because we migrated our docs from the former plugins system to the new integrations-based one, and the docs we pushed were lifted from the `main` branch, which had those features merged in, but not released yet at the time.

While the plugin has released, the docs are not up-to-date because of a problem with the actions that manage their release. I'll fix this today, and release the docs for version 1.1.5 directly afterwards.
I'll see what I can do to correct this behaviour on the v1.1.3 docs. In the meantime if you update the plugin, these attributes should now be usable.

**Comment by lbajolet-hashicorp** [comment]
Hi there,

I'll leave an update since this is still open: to my knowledge versions 1.1.5 and now 1.1.6 have those attributes documented and supported.
Version 1.1.3's documentation will remain out-of-date for now, we may be able to fix them, but this takes some effort to include the new documentation workflow on a pristine 1.1.3 branch, so we'll probably leave it as-is for now.

I'll close this issue now, but please feel free to reopen if there's something else we should do on this front.

Thanks!
