### ISSUE TITLE
Autoinstall stuck on language selection

### ISSUE THREAD

**Issue by venkateshan62** [hashicorp/packer-plugin-proxmox#265]
I'm developing ubuntu 22.04 using packer and having kickstart ubuntu22.04-cfg file. 

after boot, VM has stuck in language page.. 

please find the boot command,  which i'm using,

boot_command        =   ["e<wait><down><down><down><end>","ip=::::::dhcp::: ","autoinstall ds=nocloud ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ubuntu22.04.cfg","<wait><F10><wait>"]

ubuntu22.04.cfg- File having, root pass of user, partition details and packages installed during boot details.

please help me on this issue.

**Comment by lbajolet-hashicorp** [comment]
Hi @venkateshan62,

Regarding your question, I suggest you ask this directly over on the [community forum](https://discuss.hashicorp.com/c/packer) instead of as a Github issue, as this is mostly aimed at maintainers.
This is probably not a Packer bug at first glance, but instead has something to do with your kickstart, or with how you're triggering an automated installation with your ISO, boot commands are very OS-specific so YMMV on that front.

If you need some inspiration on what kind of boot commands to type, you may take a look at the qemu repo, there's an [example](https://github.com/hashicorp/packer-plugin-qemu/tree/main/example/efi_build) of a Debian installation with a kickstart file that goes with it. This won't work out-of-the-box for your case, but hopefully this can direct you on the right path.

I'll close this issue now as it seems to be more of a usage general question, but please feel free to reopen if I missed something!
